### ISSUE TITLE
External links are redirected to wago.io

### ISSUE THREAD

**Issue by Montrazul** [oratory/wago.io#39]
I published my first WeakAuras today at Wago.io.
I created a description and in that description I used links to external websites like:

```
I love [url=https://www.wowinterface.com/downloads/info23717-OwDUI.html]the minimalistic Overwatch UI[/url].
```
For example. But when you click on that link it just redirects you to the same wago.io page
you are currently on. You can find the WeakAuras here: https://wago.io/k_AOEZh81

**Comment by oratory** [comment]
Wago uses the battle.net API to determine if you're a human or a bot. Until your account is verified you can't actually link anything. You've connected your Bnet account but since the Bnet API likes to give 500 errors all the time (like in this case) it wasn't able to validate. Since you posted here I'll assume that you are in fact a human so I updated your account, and the links work now.

**Comment by Montrazul** [comment]
Thx.
